![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

# Tópicos da Aula de Hoje

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="400" height="200" />

- NumPy
- ndarray
  - Inicialização de Arrays

**Bora pra aula?**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# NumPy

Criado em 2005 por Travis Oliphant, o projeto NumPy foi baseado nos projetos Numeric e Numarray com o objetivo de reunir a comunidade em torno de um único framework de processamento de arrays. Portanto, o pacote NumPy, denominado dessa forma devido a abreviação de Numerical Python (Python Numérico), é uma biblioteca de código aberto destinada a realizar operações em arrays multidimensionais, amigavelmente denominada como ndarray nesta biblioteca.

Devido sua construção e funcionalidades serem baseadas na estrutura de dados ndarray, a biblioteca oferece operações rápidas para tratamento e limpeza de dados, geração de subconjuntos e filtragens, estatísticas descritivas, manipulação de dados relacionais, manipulações de dados em grupos, entre outros tipos de processamento.

Além dos recursos mais voltados a aplicações de análise de dados, no NumPy Python você também encontrará funções matemáticas para operações rápidas em arrays, sem a necessidade de escrever laços, recursos de álgebra linear, geração de números aleatórios, transformadas de Fourier, ferramentas para trabalhar com dados mapeados em memória, como também uma API para conectar o NumPy Python a bibliotecas escritas em C, C++ e FORTRAN.

[Documentação](https://numpy.org)<br>
[Código](https://github.com/numpy/numpy)

# ndarray

Um `ndarray` (abreviação de N-dimensional array) é a estrutura de dados central da biblioteca NumPy, usada para armazenar e manipular grandes conjuntos de dados numéricos de forma eficiente. É um array multidimensional que pode conter elementos de um tipo de dado específico (como inteiros, números de ponto flutuante, etc.) e permite operações rápidas e vetorizadas sobre os dados.

Características do `ndarray`:

- **Dimensionalidade:**<br>
Um ndarray pode ter uma ou várias dimensões (daí o termo "N-dimensional").
Por exemplo, um vetor (array unidimensional) é um ndarray de 1D, uma matriz (array bidimensional) é um ndarray de 2D, e um tensor pode ser um ndarray de 3D ou mais.

- **Homogeneidade:**<br>
Todos os elementos em um ndarray devem ser do mesmo tipo de dado (por exemplo, todos inteiros, todos float, etc.). Isso permite uma alocação eficiente de memória e operações rápidas.

- **Acesso aos Elementos:**<br>
Elementos de um ndarray podem ser acessados usando indexação e fatiamento, semelhante a listas em Python, mas com suporte para operações mais complexas e eficientes.

- **Operações Vetorizadas:**<br>
Um ndarray suporta operações vetorizadas, o que significa que você pode realizar operações aritméticas e outras funções em arrays inteiros sem precisar de loops explícitos. Isso torna o código mais compacto e rápido.

- **Atributos Comuns:**<br>
`shape`: Retorna uma tupla representando as dimensões do array.<br>
`dtype`: Mostra o tipo de dado dos elementos do array.<br>
`ndim`: Retorna o número de dimensões do array.<br>
`size`: Retorna o número total de elementos no array.<br>

A biblioteca NumPy fornece algumas maneiras de inicializar um ndarray:

```python
np.array()
np.zeros()
np.ones()
np.full()
np.identity()
```

**Por que `ndarray` é Importante?**

- Eficiência: O ndarray é altamente otimizado para operações numéricas, o que permite a manipulação eficiente de grandes volumes de dados.
- Flexibilidade: Suporta operações em arrays de qualquer dimensão, tornando-o essencial para computação científica e análise de dados.
- Compatibilidade: A maioria das funções e operações em NumPy retornam ou operam sobre ndarray, o que faz dele a base para muitas outras bibliotecas e frameworks no ecossistema Python.

O ndarray é, portanto, a estrutura fundamental em NumPy para trabalhar com arrays multidimensionais e desempenha um papel crucial na ciência de dados, machine learning, e outras áreas que envolvem computação numérica intensiva.

In [ ]:
# posso iniciar com uma lista
lista = [ 1,2,3]
# criação do array:
np_array = np.array(lista, dtype=int)

In [ ]:
print(lista)

[1, 2, 3]


In [ ]:
print(np_array)

[1 2 3]


In [ ]:
for i in range(len(lista)):
    lista[i] *= 2
print(lista)

[2, 4, 6]


In [ ]:
print(np_array)

[1 2 3]


In [ ]:
np_array*2

array([2, 4, 6])

In [ ]:
# tipo
type(np_array)

numpy.ndarray

In [ ]:
np_array

array([1, 2, 3])

In [ ]:
# numero de dimensoes
np_array.ndim

1

In [ ]:
# shape
np_array.shape

(3,)

In [ ]:
# tamanho (numero de elementos)
np_array.size

3

In [ ]:
# Arrays de 1 e 0
# zeros
z = np.zeros((3,1))
z

array([[0.],
       [0.],
       [0.]])

In [ ]:
# uns
u = np.ones((3,3), float)
u

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
z = np.zeros((2,3,2))
z

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
type(z)

numpy.ndarray

In [ ]:
z.shape

(2, 3, 2)

In [ ]:
z.ndim

3

In [ ]:
print(u)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
np.full((2,3), 100.)

array([[100., 100., 100.],
       [100., 100., 100.]])

In [ ]:
np.random.rand(3,3)

array([[0.17868379, 0.94626448, 0.32716763],
       [0.08433608, 0.77706337, 0.13041883],
       [0.88220458, 0.19068534, 0.44213802]])

In [ ]:
np.random.randint(-4,8, size=(5,))

array([ 6,  2,  3, -4, -3])

# Exercícios

Crie um array 3D com dimensões 3x4x5 contendo números aleatórios inteiros entre 0 e 50.

Crie dois arrays 2D de dimensões 4x4 com valores aleatórios entre 1 e 10.

Crie um array de dimensão 5x5 com valores aleatórios entre 10 e 100. Normalize os valores do array de modo que todos os elementos estejam no intervalo de 0 a 1.