![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

# Tópicos da Aula de Hoje

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="400" height="200" />

- Manipulação das dimensões de um Array
  - reshape
  - flattening
  - transpose
  - expand_dims
  - squeeze
  - resize

**Bora pra aula?**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# Manipulação das dimensões de um array

Manipulação das dimensões de um array refere-se ao processo de alterar a forma (ou estrutura dimensional) de um array, sem modificar os dados nele contidos. Isso é extremamente útil em tarefas que envolvem análise e processamento de dados, onde diferentes operações podem exigir arrays de dimensões específicas.

No NumPy, essa manipulação é feita principalmente através de funções como `reshape`, `ravel`, `flattening`, `transpose`, `expand_dims`, `squeeze`, `resize`, entre outras.



**Por que Manipular as Dimensões de um Array?**

- Compatibilidade: Diferentes operações ou algoritmos podem exigir arrays de formatos específicos.
- Eficiência: Otimiza o uso de memória e processamento, especialmente em operações vetorizadas.
- Flexibilidade: Facilita a implementação de operações como soma, multiplicação matricial, ou qualquer outra manipulação de dados em diferentes formatos.

**Considerações Importantes**

- Consistência dos Dados: Ao manipular as dimensões, o número total de elementos deve ser preservado (exceto em casos de resize que altera o tamanho do array).
- Broadcasting: Manipular dimensões é uma etapa chave para preparar arrays para operações de broadcasting, onde arrays de diferentes formas podem ser combinados em operações aritméticas.

## Reshape

In [ ]:
narray = np.full((2,6),0.45)
narray

array([[0.45, 0.45, 0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45, 0.45, 0.45]])

In [ ]:
n = 2
m = 6

In [ ]:
produto = 2*6
print(produto)

12


possibilidades:
- 3*4
- 6*2
- 4*3
- 1*12

In [ ]:
narray = narray.reshape(3,4) # importante notar o retorno de reshape

In [ ]:
narray

array([[0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45]])

In [ ]:
# se tentar reshape para um formato com mais de 12 elementos?
narray.reshape(3,7)

ValueError: cannot reshape array of size 12 into shape (3,7)

In [ ]:
narray.reshape(2,6)

array([[0.45, 0.45, 0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45, 0.45, 0.45]])

In [ ]:
narray.reshape(12,1)

array([[0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45],
       [0.45]])

In [ ]:
narray.reshape(1,12)

array([[0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
        0.45]])

## Ravel/Flatten

O comando ravel transforma o array em um array 1D. Flatten e ravel são análogos

In [ ]:
# ravel
narray = np.full((3,4),0.45)
print(narray)

[[0.45 0.45 0.45 0.45]
 [0.45 0.45 0.45 0.45]
 [0.45 0.45 0.45 0.45]]


In [ ]:
narray.ravel()

array([0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
       0.45])

In [ ]:
narray.flatten()

array([0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
       0.45])

In [ ]:
narray

array([[0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45]])

In [ ]:
narray = narray.flatten()
narray

array([0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
       0.45])

## Transpose

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

## Expand Dims

A função `np.expand_dims` aumenta o número de dimensões de um array, o que pode ser útil em operações de broadcast ou quando uma função espera um array de maior dimensionalidade.

In [ ]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [ ]:
array.shape

(3,)

In [ ]:
exp = np.expand_dims(array, axis=1)
exp

array([[1],
       [2],
       [3]])

In [ ]:
exp.shape

(3, 1)

## Squeeze

A função `squeeze` remove dimensões de tamanho 1 de um array, simplificando sua estrutura dimensional.

In [ ]:
exp

array([[1],
       [2],
       [3]])

In [ ]:
array_squeezed = np.squeeze(exp)
array_squeezed

array([1, 2, 3])

In [ ]:
array_squeezed.shape

(3,)

## Resize

In [ ]:
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [ ]:
array_resized = np.resize(array, (2, 3))
array_resized

array([[1, 2, 3],
       [4, 1, 2]])

In [ ]:
array_resized = np.resize(array, (4, 2))
array_resized

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

# Exercícios

Crie um array unidimensional contendo 16 números inteiros sequenciais. Em seguida, redimensione o array para formar uma matriz 4x4.

In [ ]:
array = np.array(range(16))
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
array = np.reshape(array, (4,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Crie uma matriz 3x4 com valores aleatórios. Aplique a operação de flattening para converter a matriz em um array unidimensional. Em seguida, reorganize o array unidimensional em uma matriz 2x6.

Crie um array unidimensional de tamanho 5. Expanda as dimensões do array para transformá-lo em um vetor coluna (5x1) e, em seguida, em um vetor linha (1x5).

Crie um array 3D de dimensões 2x3x4 com valores aleatórios. Permute os eixos do array para que o eixo das linhas (primeira dimensão) troque de lugar com o eixo das colunas (segunda dimensão).