![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

# Tópicos da Aula de Hoje

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="400" height="200" />

- Indexação de Arrays
  - np.where
- Fatiamento de Arrays
- Operações Matemáticas Simples

**Bora pra aula?**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

## Indexação

*  É possível indexar um array usando índices inteiros
*  Usando uma lista de booleanos
*  Usando lista de inteiros

In [ ]:
a = np.array( [1, 2, 3] )
a

array([1, 2, 3])

In [ ]:
b = np.array( [[2, 3, 4], [5, 6, 7]] )
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
a[0]

1

In [ ]:
a[1]

2

In [ ]:
a[2]

3

In [ ]:
a

array([1, 2, 3])

In [ ]:
for i in a:
    print(i)

1
2
3


In [ ]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
b[0]

array([2, 3, 4])

In [ ]:
type(b[0])

numpy.ndarray

In [ ]:
b[1]

array([5, 6, 7])

In [ ]:
b[0, 0]

2

In [ ]:
b[1, 2]

7

In [ ]:
a.shape

(3,)

In [ ]:
b[1, 2]

7

In [ ]:
print(a[0])
print(b[0, 1])
print(b[1, 2])

1
3
7


In [ ]:
3 > 1

True

In [ ]:
a

array([1, 2, 3])

In [ ]:
a>1

array([False,  True,  True])

E se eu fizer a mesma coisa com b?

In [ ]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
b > 3

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
b[b>3]

array([4, 5, 6, 7])

In [ ]:
type(b[b>3])

numpy.ndarray

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[a == 1]

array([1])

In [ ]:
a[a>1]

array([2, 3])

In [ ]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
b > 3

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
b[b > 3]

array([4, 5, 6, 7])

```python
np.where(condition, [x,y,...])
```

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.where(a > 1, a, 0)

array([0, 2, 3])

In [ ]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
np.where(b > 3, b, -1)

array([[-1, -1,  4],
       [ 5,  6,  7]])

In [ ]:
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
b[0,0]

2

In [ ]:
b[0,0] = 200

In [ ]:
b

array([[200,   3,   4],
       [  5,   6,   7]])

## Fatiamento em Arrays

Fatiamento em arrays (ou slicing em inglês) é uma técnica usada para acessar subconjuntos de elementos em um array. No contexto de NumPy e outras bibliotecas que manipulam dados, o fatiamento permite selecionar partes específicas de um array sem precisar copiar ou alterar o array original.

```python
array[início:fim:passo]
```

- `início`: O índice inicial do fatiamento (inclusivo). O padrão é 0.
- `fim`: O índice final do fatiamento (exclusivo). O padrão é o tamanho do array.
- `passo`: O tamanho do passo entre os índices. O padrão é 1.

In [ ]:
lista = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [ ]:
lista

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [ ]:
lista[0][0]

0

In [ ]:
mat = np.array(lista)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
mat[ 0, 0:3 ]

array([0, 1, 2])

In [ ]:
mat[1, 1:3]

array([5, 6])

In [ ]:
mat.shape

(3, 4)

In [ ]:
mat[0,0]

0

In [ ]:
mat[0,0] = 100
mat

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [ ]:
mat[0,:]

array([100,   1,   2,   3])

In [ ]:
mat[:,0]

array([100,   4,   8])

In [ ]:
mat[:,2]

array([ 2,  6, 10])

In [ ]:
mat[0,0] = 100
mat

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [ ]:
mat[:,0]

array([100,   4,   8])

In [ ]:
#  É possível atribuir uma linha/coluna de uma vez?
mat[:,0] = [200, 8, 16]
mat

array([[200,   1,   2,   3],
       [  8,   5,   6,   7],
       [ 16,   9,  10,  11]])

## Operações Matemáticas

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
a

array([1, 2, 3, 4])

# Exercícios

Crie um array 2D de dimensões 5x5 com valores inteiros aleatórios entre 1 e 20. Use a indexação booleana para substituir todos os valores maiores que 10 por 100.

Crie um array 1D contendo 10 números inteiros aleatórios entre 1 e 50. Em seguida, crie um array de índices aleatórios de tamanho 5 e use-o para extrair elementos específicos do array original.

Crie uma matriz 5x5 com valores inteiros consecutivos de 1 a 25. Em seguida, extraia uma submatriz 3x3 do centro da matriz.

Crie um array 1D de tamanho 10 com valores aleatórios entre 0 e 50. Substitua todos os elementos entre as posições 3 e 7 (inclusive) por zero.

Crie um array 1D contendo números de 1 a 20. Extraia um subarray contendo apenas os elementos em posições ímpares.

Crie um array 3D de dimensões 3x4x5 com valores inteiros aleatórios entre 1 e 100. Extraia todos os elementos da segunda camada (segunda dimensão) do array.

Crie dois arrays 2D de dimensões 3x3 com valores inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento a elemento.

Crie um array 2D de dimensão 3x3 com valores inteiros aleatórios entre 1 e 10. Subtraia de cada linha do array o valor mínimo da respectiva linha.

Crie dois arrays 1D de tamanho 3 com valores inteiros aleatórios entre 1 e 10. Calcule o produto escalar dos dois arrays. Em seguida, crie dois arrays 2D de dimensões 3x3 e calcule o produto matricial entre eles.