![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="400" height="200" />

- Funções Matemáticas
- Operações entre arrays

**Bora pra aula?**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

## Funções Matemáticas

O Numpy possui algumas funções e submódulos que auxiliam nosso dia a dia.

In [ ]:
# Média
np.mean( [1,2,3,4] )

2.5

In [ ]:
np.sum([1,2,3,4] )

10

In [ ]:
# Desvio Padrão
np.std([1,2,3,4])

1.118033988749895

In [ ]:
#mediana
np.median([1,2,3,4])

2.5

In [ ]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.mean()

4.5

In [ ]:
np.mean(a)

4.5

In [ ]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
array2D_1 = array.reshape((3,3))
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Média da linha
np.mean(array2D_1, axis=1)

array([1., 4., 7.])

In [ ]:
# Média da coluna
np.mean( array2D_1, axis=0)

array([3., 4., 5.])

In [ ]:
array2D_1.mean(axis=0)

array([3., 4., 5.])

In [ ]:
# Soma da coluna
np.sum( array2D_1, axis=0)

array([ 9, 12, 15])

In [ ]:
# Soma da linha
np.sum( array2D_1, axis=1)

array([ 3, 12, 21])

As funções acima aceitam axis

O np.arange cria um vetor espaçado entre dois números.

In [ ]:
np.array(range(1, 20, 2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# np.arange
x = np.arange(start=1, stop=20, step=2) #as 3 opçoes do arange
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
x = np.arange(1, 20, 2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
%%timeit
[x for x in range(1, 100000, 1)]

2.43 ms ± 591 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
np.arange(start=1, stop=100000, step=1)

26.2 µs ± 914 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
np.arange(5, 10, 0.2)

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4,
       7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [ ]:
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
np.random.shuffle(x)
print(x)

[15 11  1  9  7  3 19 17  5 13]


In [ ]:
x

array([15, 11,  1,  9,  7,  3, 19, 17,  5, 13])

np.linspace gera um array de n números entre dois valores.

In [ ]:
# np.linspace
a = np.linspace(start=1, stop=10, num=100)
a

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
a.shape

(100,)

In [ ]:
# np.where
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x[np.where( x%2 == 0 )]

array([0, 2, 4, 6, 8])

O submódulo random do numpy pode ser utilizado para gerar números aleatórios, selecionar e embaralhar números.

In [ ]:
caixa = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
# escolha aleatória
np.random.choice(caixa, 5, replace=False)

array([0, 1, 1, 0, 1])

In [ ]:
# embaralhamento
x = [1,2,3]
np.random.shuffle(x)
x

[3, 2, 1]

## Operações entre Arrays

In [ ]:
array1 = np.arange(9)
array2 = np.arange(9)

In [ ]:
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [ ]:
# Soma
array1 + array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
# Subtração
array1 - array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Divisão
array1/array2

/var/folders/zm/3bssg1p14lj63wq1qny6y2qh0000gn/T/ipykernel_6349/2940787987.py:2: RuntimeWarning: invalid value encountered in divide
  array1/array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Multiplicação
array1*array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

E se tentarmos fazer operações com listas???

In [ ]:
[1,2,3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [ ]:
[1,2,3]*[4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
[1,2,3]/[4, 5, 6]

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
[1,2,3]-[4, 5, 6]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# Exercícios

Crie um array 1D de tamanho 10 com valores igualmente espaçados entre 0 e π. Aplique as funções sin, cos, e tan em cada elemento do array e exiba os resultados.

Crie um array 1D de tamanho 10 com valores inteiros aleatórios entre 1 e 100. Aplique as funções exp, log, log10, e sqrt aos elementos do array e exiba os resultados.

Crie um array 2D de dimensões 4x4 com valores inteiros aleatórios entre 0 e 50. Calcule a média, o desvio padrão, a variância, o valor mínimo, e o valor máximo de cada linha e coluna do array.

Crie dois arrays 2D de dimensões 3x3 com valores inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação, e divisão elemento a elemento entre os dois arrays.

Crie dois arrays 1D de tamanho 5 com valores inteiros aleatórios entre 1 e 10. Calcule o produto escalar entre os dois arrays. Em seguida, crie dois arrays 2D de dimensões 3x3 e calcule o produto matricial entre eles.

Crie um array 2D de dimensão 4x4 com valores inteiros aleatórios entre 1 e 10. Subtraia de cada linha do array o valor mínimo de cada linha. Em seguida, divida cada coluna do array pelo valor máximo de cada coluna.

Crie dois arrays 2D de dimensões 3x3 com valores inteiros aleatórios entre 1 e 15. Compare os arrays elemento a elemento, gerando um array booleano que indica onde os elementos do primeiro array são maiores que os do segundo array.