# Exercícios Numpy

In [1]:
import numpy as np

Crie um array 3D com dimensões 3x4x5 contendo números aleatórios inteiros entre 0 e 50.

In [2]:
array = np.random.randint(0, 50, (3,4,5))
array

array([[[26, 46, 43,  5, 43],
        [ 8, 28, 25,  1, 47],
        [39, 32, 44,  9, 16],
        [43, 35,  0, 33, 47]],

       [[13, 31, 19, 48, 21],
        [19, 18, 10, 17,  7],
        [43, 31, 22, 30, 32],
        [13,  6, 33, 40, 15]],

       [[32,  7, 17,  8, 25],
        [22, 26, 21,  6, 48],
        [ 0,  6, 39, 27,  8],
        [ 3, 17, 20,  1, 23]]])

In [3]:
array.shape

(3, 4, 5)

Crie uma matriz 3x4 com valores aleatórios. Aplique a operação de flattening para converter a matriz em um array unidimensional. Em seguida, reorganize o array unidimensional em uma matriz 2x6.

In [4]:
array = np.random.randint(0, 10, (3,4))
array

array([[6, 0, 4, 2],
       [9, 0, 0, 0],
       [7, 9, 1, 2]])

In [5]:
array_flat = array.flatten()
array_flat

array([6, 0, 4, 2, 9, 0, 0, 0, 7, 9, 1, 2])

In [7]:
array_2d = array_flat.reshape((2,6))
array_2d

array([[6, 0, 4, 2, 9, 0],
       [0, 0, 7, 9, 1, 2]])

Crie um array 2D de dimensões 5x5 com valores inteiros aleatórios entre 1 e 20. Use a indexação booleana para substituir todos os valores maiores que 10 por 100.

In [8]:
array = np.random.randint(1, 20, (5,5))
array

array([[16,  6,  1, 17,  9],
       [14,  2, 12,  3, 13],
       [14,  6,  1, 17, 17],
       [14,  3,  7, 14, 16],
       [ 9,  6,  8, 16, 19]])

In [9]:
array_new = np.where(array>10, 100, array)
array_new

array([[100,   6,   1, 100,   9],
       [100,   2, 100,   3, 100],
       [100,   6,   1, 100, 100],
       [100,   3,   7, 100, 100],
       [  9,   6,   8, 100, 100]])

Crie dois arrays 2D de dimensões 3x3 com valores inteiros aleatórios entre 1 e 20. Combine esses dois arrays tanto verticalmente quanto horizontalmente usando vstack e hstack, respectivamente.

In [10]:
array1 = np.random.randint(1, 20, (3,3))
array1

array([[ 2,  7, 19],
       [ 7,  7,  4],
       [ 9, 10,  6]])

In [11]:
array2 = np.random.randint(1, 20, (3,3))
array2

array([[ 8,  1,  5],
       [ 9, 10,  2],
       [ 6,  7,  9]])

In [12]:
array_v = np.vstack((array1, array2))
array_v

array([[ 2,  7, 19],
       [ 7,  7,  4],
       [ 9, 10,  6],
       [ 8,  1,  5],
       [ 9, 10,  2],
       [ 6,  7,  9]])

In [13]:
array_h = np.hstack((array2, array1))
array_h

array([[ 8,  1,  5,  2,  7, 19],
       [ 9, 10,  2,  7,  7,  4],
       [ 6,  7,  9,  9, 10,  6]])

Crie um array 1D de tamanho 10 com valores igualmente espaçados entre 0 e π. Aplique as funções sin, cos, e tan em cada elemento do array e exiba os resultados.

In [14]:
import math

In [15]:
array = np.linspace(0, math.pi, 10)
array

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [16]:
np.sin(array)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

In [17]:
np.cos(array)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])

In [18]:
np.tan(array)

array([ 0.00000000e+00,  3.63970234e-01,  8.39099631e-01,  1.73205081e+00,
        5.67128182e+00, -5.67128182e+00, -1.73205081e+00, -8.39099631e-01,
       -3.63970234e-01, -1.22464680e-16])