![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

# Tópicos da Aula de Hoje

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png" width="400" height="200" />

- Manipulação entre Arrays:
  - vstack/hstack
  - concatenate
  - append

**Bora pra aula?**

In [1]:
!pip install numpy

In [2]:
import numpy as np

# Manipulação de Arrays

## hstack/vstack

As funções `hstack` e `vstack` do NumPy são usadas para combinar arrays ao longo de diferentes eixos, facilitando a criação de arrays maiores a partir de arrays menores.

**`hstack`:** A função hstack empilha arrays horizontalmente, ou seja, ao longo do eixo das colunas. Para arrays 2D, isso significa que os arrays são concatenados lado a lado.<br>
**`vtsack`:** A função vstack empilha arrays verticalmente, ou seja, ao longo do eixo das linhas. Para arrays 2D, isso significa que os arrays são concatenados um sobre o outro.

**Comparação**

`hstack`: Utilizado para adicionar mais colunas aos arrays existentes. Útil quando se quer concatenar dados que possuem a mesma estrutura de linha.

`vstack`: Utilizado para adicionar mais linhas aos arrays existentes. Útil quando se quer empilhar dados com a mesma estrutura de coluna.

In [3]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.array([1, 1, 1])

In [4]:
a

array([1, 2, 3])

In [5]:
b

array([2, 3, 4])

In [6]:
c

array([1, 1, 1])

In [9]:
c.shape

(3,)

In [7]:
d = np.vstack((c,a,b))
d

array([[1, 1, 1],
       [1, 2, 3],
       [2, 3, 4]])

In [8]:
d.shape

(3, 3)

In [10]:
np.vstack((c, b, a, b))

array([[1, 1, 1],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [11]:
a

array([1, 2, 3])

In [13]:
b

array([2, 3, 4])

In [12]:
c

array([1, 1, 1])

In [14]:
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
c

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
type(c)

numpy.ndarray

**Observações**: 
- Recebe uma tupla como entrada
- Arrays podem ter mais de uma dimensão
- Retorna uma variável nova

In [17]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [20]:
a.shape

(3,)

In [21]:
b.shape

(3,)

In [22]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])

In [23]:
a

array([[1],
       [2],
       [3]])

In [24]:
a.shape

(3, 1)

In [25]:
b

array([[2],
       [3],
       [4]])

In [26]:
b.shape

(3, 1)

In [28]:
c = np.hstack((a,b))
c

array([[1, 2],
       [2, 3],
       [3, 4]])

In [29]:
c.shape

(3, 2)

## append

A função `numpy.append` é utilizada para adicionar elementos ao final de um array. Ao contrário das funções `hstack` e `vstack`, que são usadas para combinar arrays ao longo de eixos específicos, append permite adicionar novos elementos (ou arrays) ao final de um array existente.

In [30]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [31]:
a

array([1, 2, 3])

In [32]:
b

array([2, 3, 4])

In [33]:
np.append(a, b) 

array([1, 2, 3, 2, 3, 4])

In [34]:
a = np.array( [[1,2,3], [4,5,6]] )
b = np.array([2,3,4])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b

array([2, 3, 4])

In [37]:
np.append(a, b) 

array([1, 2, 3, 4, 5, 6, 2, 3, 4])

In [41]:
a = np.array( [[1,2,3], [4,5,6]] )
b = np.array([2,3,4]).reshape(1, 3)

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
b

array([[2, 3, 4]])

In [44]:
np.append(a, b, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [45]:
b = np.array([2,3,4])
b

array([2, 3, 4])

In [46]:
b.shape

(3,)

In [47]:
b.ndim

1

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
b

array([2, 3, 4])

In [50]:
np.append((a,b), axis=1)

TypeError: append() missing 1 required positional argument: 'values'

In [53]:
a = np.array( [[1,2,3], [4,5,6]] )
b = np.array([[2,3,4], [1,1,1]])
np.append(a, b, axis=1)

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 1, 1, 1]])

## Concatenate

A função `numpy.concatenate` é usada para juntar arrays ao longo de um eixo específico, semelhante às funções `hstack` e `vstack`. No entanto, concatenate oferece mais flexibilidade em termos de escolha do eixo ao longo do qual a concatenação deve ocorrer.

`axis=0`: Adiciona linhas<br>
`axis=1`: Adiciona colunas

`concatenate` oferece controle total sobre o eixo ao longo do qual a concatenação é realizada, permitindo a combinação de arrays ao longo de eixos diferentes.
`hstack` e `vstack` são mais específicos e simplificados para casos comuns de empilhamento horizontal e vertical, respectivamente.

In [54]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
array2D_1 = array.reshape((3,3))
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
array2D_2 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18]).reshape((3,3))
array2D_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [57]:
# concatenação vertical -> vstack
np.concatenate((array2D_1, array2D_2), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [58]:
# concatenação horizontal -> hstack
np.concatenate((array2D_1,array2D_2), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [59]:
# E como concatenar mais de 2 arrays
np.concatenate((array2D_1, array2D_2, array2D_1, array2D_1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [60]:
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
np.concatenate((array2D_1, np.arange(6).reshape(2,3)), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [64]:
np.concatenate((array2D_1, np.arange(9).reshape(3,3)))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Exercícios

Crie dois arrays 2D de dimensões 3x3 com valores inteiros aleatórios entre 1 e 20. Combine esses dois arrays tanto verticalmente quanto horizontalmente usando vstack e hstack, respectivamente.

Crie três arrays 1D de tamanhos 3, 5, e 7, respectivamente, com valores inteiros aleatórios entre 1 e 50. Use concatenate para combinar esses arrays em um único array 1D. Em seguida, crie dois arrays 2D de dimensões 3x3 e 3x2, e concatene-os ao longo do eixo 1 (horizontalmente).

Crie um array 1D de tamanho 5 com valores inteiros aleatórios entre 1 e 20. Use append para adicionar três novos elementos ao final do array e, em seguida, adicione dois novos elementos no início.

Crie dois arrays 2D: o primeiro com dimensão 2x3 e o segundo com dimensão 3x2, ambos com valores inteiros aleatórios entre 1 e 10. Combine esses arrays verticalmente e horizontalmente utilizando concatenate, ajustando os eixos adequadamente.

Crie três arrays 1D de tamanhos diferentes (4, 6, 8) e valores inteiros aleatórios entre 1 e 30. Utilize vstack para empilhar os arrays verticalmente e hstack para empilhá-los horizontalmente após ajustá-los para terem o mesmo número de colunas.

Crie um array 3D de dimensões 3x3x3 com valores inteiros aleatórios entre 1 e 100. Adicione uma nova camada (terceira dimensão) com valores inteiros sequenciais de 101 a 109. Em seguida, adicione uma nova linha no início de cada camada.